### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by damwhit** [judithpillado/mod_0_skills#1]
@judithpillado overall, nice work on this. You did not do great on part 3, but you did a well enough on the OOP portion of the assessment so we're give you a chance to make some updates that can make you `technical ready`! Please make the following updates by eod Saturday:

* [x]  Make your quotes consistent. Pick either double or single
* [x] Make sure that all of your methods read as verbs
* [x] Make sure all of your arrays are named plurally, per convention
* [x] Add another method for each class and instance, utilizing one or more of the attributes that are already defined

* [x] Part 3:
  * You didn’t get 6, 9, or 10. Please go over them again and make your corrections

**Comment by judithpillado** [comment]
Hi David, 

Thank you for your comments! I updated everything you asked and I pushed the results to Github. Please let me know if something doesn't look right or if you have any more suggestions. I really appreciate your feedback. Thanks!

**Comment by damwhit** [comment]
@judithpillado it's almost there. Please go back and make sure that all methods are reading as action words or phrases and then it'll be ready

**Comment by judithpillado** [comment]
@damwhit I'm a little confused because I thought that the action words I'm using, such as: add, calculate, bite, divide, and multiply were okay to use... Can you tell me what part of my methods is incorrect?

**Comment by damwhit** [comment]
@judithpillado `tomato` and `white_bread` from class 1. `bacon` and `fresh_mushroom` in class. All of your other methods look fine, but I expected you to go back and correct all of them

**Comment by judithpillado** [comment]
@damwhit Sorry I didn't understand what you meant, but thanks for the clarification! I fixed the issue you pointed out and I believe all my methods read as verbs now.

**Comment by damwhit** [comment]
No worries. Updates look good! You are officially `technical ready`! Keep up the hard work moving forward!
